CREATE TABLE OrderChef
(
	IsBusy BIT NOT NULL DEFAULT 0,

	UserId INT FOREIGN KEY REFERENCES ApplicationUser(Id) NOT NULL,
	OrderId INT FOREIGN KEY REFERENCES FoodOrder(Id) NOT NULL,
	EntityId INT NULL,

	CONSTRAINT FK_OrderChef_Entity FOREIGN KEY (EntityId) REFERENCES Entity(Id)
)
