CREATE TABLE Entity(
	Id INT PRIMARY KEY IDENTITY(1000, 1) NOT NULL,
	EntityName VARCHAR(150) NOT NULL,
	Currency VARCHAR(10) NULL,

	IsDeleted BIT NOT NULL DEFAULT 0,
	CreatedBy INT NULL,
	CreatedOn DATE NULL,
	ModifiedBy INT NULL,
	ModifiedOn DATE NULL,
);