CREATE TABLE OrderTypeList
(
	[Id] INT PRIMARY KEY IDENTITY(1000, 1) NOT NULL,
	[Name] VARCHAR(150) NOT NULL,

	[EntityId] INT NULL,

	CONSTRAINT FK_OrderTypeList_Entity FOREIGN KEY (EntityId) REFERENCES Entity(Id)
)
