CREATE TABLE OrderStatusList
(
	Id INT PRIMARY KEY IDENTITY(1000, 1) NOT NULL,
	OrderStatusName VARCHAR(150) NOT NULL,

	EntityId INT NULL,

	CONSTRAINT FK_OrderStatusList_Entity FOREIGN KEY (EntityId) REFERENCES Entity(Id)
);
